### ISSUE TITLE
Problem installing on Windows 10

### ISSUE THREAD

**Issue by byeze** [Streampunk/naudiodon#46]
When installing **naudiodon**, node-gyp throws errors and warnings and it exists. This is the output of the terminal:

```
npm install naudiodon

> segfault-handler@1.3.0 install C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler
> node-gyp rebuild


C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "-m".
  segfault-handler.cpp
  StackWalker.cpp       
  win_delay_load_hook.cc
C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\includes\StackWalker.h(120): warning C4091: 'typedef ': se ha omitido a la izquierda de 'StackWalker::CallstackEntryTy
pe' cuando no hay ninguna variable declarada (compilando archivo de origen ..\src\StackWalker.cpp) [C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\build\segfault-han
dler.vcxproj]
C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\src\StackWalker.cpp(356): warning C4091: 'typedef ': se ha omitido a la izquierda de 'StackWalkerInternal::IMAGEHLP_MO
DULE64_V2' cuando no hay ninguna variable declarada [C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\build\segfault-handler.vcxproj]
C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\includes\StackWalker.h(120): warning C4091: 'typedef ': se ha omitido a la izquierda de 'StackWalker::CallstackEntryTy
pe' cuando no hay ninguna variable declarada (compilando archivo de origen ..\src\segfault-handler.cpp) [C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\build\segfaul
t-handler.vcxproj]
C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\src\segfault-handler.cpp(210,69): warning C4311: 'conversión de tipo': truncamiento de puntero de 'PVOID' a 'long' [C:
\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\build\segfault-handler.vcxproj]
C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\src\segfault-handler.cpp(210,69): warning C4302: 'conversión de tipo': truncamiento de 'PVOID' a 'long' [C:\Users\Usua 
rio\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\build\segfault-handler.vcxproj]
C:\\Users\\Usuario\\AppData\\Local\\node-gyp\\Cache\\12.16.3\\x64\\node.lib : fatal error LNK1127: la biblioteca está dañada [C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault- 
handler\build\segfault-handler.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.0 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! segfault-handler@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\src\segfault-handler.cpp(210,69): warning C4302: 'conversión de tipo': truncamiento de 'PVOID' a 'long' [C:\Users\Usua 
rio\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler\build\segfault-handler.vcxproj]
C:\\Users\\Usuario\\AppData\\Local\\node-gyp\\Cache\\12.16.3\\x64\\node.lib : fatal error LNK1127: la biblioteca está dañada [C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault- 
handler\build\segfault-handler.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Usuario\Desktop\Eze\Proyectos\timekode\node_modules\segfault-handler
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.0 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! segfault-handler@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segfault-handler@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usuario\AppData\Roaming\npm-cache\_logs\2020-05-18T16_35_54_230Z-debug.log
```

**Comment by IrregularShed** [comment]
I had this problem as well (at least it looks like the same problem, my Spanish isn't good enough to know for sure). I did some digging and found this - once I'd followed the instructions it all built and installed fine.

https://github.com/nodejs/node-gyp#option-1

**Comment by byeze** [comment]
Yeah, I followed that and tried to build, but the error is still appearing. I'll try to look it more deeply and make sure isn't my error haha.

**Comment by FujiwaraChoki** [comment]
@byeze Were you able to solve the issue?
