### ISSUE TITLE
Record sound from speakers

### ISSUE THREAD

**Issue by alex-erygin** [Streampunk/naudiodon#50]
Cannot record sound from speakers on mac os.
```js

var speakers = new portAudio.AudioIO({
    inOptions: {
        channelCount: 1,
        sampleFormat: portAudio.SampleFormat16Bit,
        sampleRate: 44100,
        deviceId: 1, // Use -1 or omit the deviceId to select the default device
        closeOnError: true // Close the stream if an audio error is detected, if set false then just log the error
    }
})


var ws = fs.createWriteStream('speakerz.raw');
speakers.pipe(ws);
speakers.start();
```

Output is:
```
Input audio options: device 1, sample rate 44100, channels 1, bits per sample 16, max queue 2, frames per buffer 0, close on error true
Input device name is Динамики «MacBook Pro»
/Users/alexandererygin/projects/sound_node/node_modules/naudiodon/index.js:32
  const audioIOAdon = new portAudioBindings.AudioIO(options);
                      ^

Error: Channel count exceeds maximum number of channels for device
    at new AudioIO (/Users/alexandererygin/projects/sound_node/node_modules/naudiodon/index.js:32:23)
    at Object.<anonymous> (/Users/alexandererygin/projects/sound_node/app.js:17:16)
```

**Comment by Mola19** [comment]
Yes, cou can't record an output device, only ouput sound. This would require loopback audio, which is as far as i know not implemented in naudiodon, which unfortunate, because i need it and there seems to be no real node package that does that.

**Comment by madaghafuri** [comment]
anyone have un updated resource regarding loopback recording? Or anyone has a fork oh naudiodon that supports loopback recording?

**Comment by 64jcl** [comment]
Ah, came here just to find this. The package looked so nice but need loopback. Audacity supports this just fine by selecting e.g. anything from Windows WASAPI host. If anyone can help that would be awesome. Need it to stream sound from an emulator.
