### ISSUE TITLE
Error: node-gyp failed to rebuild segfault-handler

### ISSUE THREAD

**Issue by matiasmm** [Streampunk/naudiodon#74]
I'm using electron, and I'm having an issue when I run `npm run electron-rebuild`

```
Matias@ ~/audio/release/app % npm run electron-rebuild
yarn run v1.22.17
$ DEBUG=true node -r ts-node/register ../../.erb/scripts/electron-rebuild.js
⠸ Building modules: 1/3  COPY ../build/Release/libportaudio.dylib
  COPY ../build/Release/libportaudio.dylib
  CXX(target) Release/obj.target/naudiodon/src/naudiodonUtil.o
  CXX(target) Release/obj.target/naudiodon/src/naudiodonUtil.o
⠹ Building modules: 1/3  CXX(target) Release/obj.target/naudiodon/src/naudiodon.o
  CXX(target) Release/obj.target/naudiodon/src/naudiodon.o
⠙ Building modules: 1/3  CXX(target) Release/obj.target/naudiodon/src/GetDevices.o
  CXX(target) Release/obj.target/naudiodon/src/GetDevices.o
⠧ Building modules: 1/3rm: ./Release/.deps/Release/obj.target/naudiodon/src/GetDevices.o.d.raw: No such file or directory
make: *** [Release/obj.target/naudiodon/src/GetDevices.o] Error 1
✖ Rebuild Failed
  CXX(target) Release/obj.target/naudiodon/src/GetHostAPIs.o

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/Matias/audio/release/app/node_modules/segfault-handler'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2



Error: node-gyp failed to rebuild '/Users/Matias/audio/release/app/node_modules/segfault-handler'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2


    at NodeGyp.rebuildModule (/Users/Matias/audio/node_modules/electron-rebuild/lib/src/module-type/node-gyp.js:109:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Command failed: ../../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (/Users/Matias/audio/.erb/scripts/electron-rebuild.js:17:11)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/Matias/audio/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/Matias/audio/node_modules/ts-node/src/index.ts:1368:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 46872,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Help would be very appreciated

**Comment by palash-sarate** [comment]
did you find any solution to this problem ?
